version: "3.8"


services:
  gui:
    image: gui
    ports:
      - "3001:3000"
    environment:
      GUI_API_ROUTE: gui-service/api
      NODE_ENV: development
    deploy:
      replicas: 3 
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
       - gui-back-auth-1

  auth:
    image: auth
    ports:
      - "4000:4000"
    environment:
      AUTH_API_ROUTE: auth-service/api
      MONGO_URI: db-secret-uri
      JWT_SECRET: db-secret-jwt
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
       - gui-back-auth-1
       - mongo-back-auth-1

  studclass:
    image: studclass
    ports:
      - "5000:5000"
    environment:
      studclass_API_ROUTE: studclass-service/api
      MONGO_URI: db-secret-uri
      NODE_ENV: development
    depends_on: 
      - mongo
    networks:
       - gui-back-auth-1
       - mongo-back-auth-1

  mongo:
    image: mongo:4.4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/mongo
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
       - mongo-back-auth-1
       - adminer-1

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
     - "8082:8082"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: db-secret-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: db-secret-password
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
       - adminer-1

  visualizer:
   image: dockersamples/visualizer:stable
   ports: 
     - "8081:8080"
   stop_grace_period: 1m30s
   volumes:
     - "/var/run/docker .sock:/var/run/docker .sock"
   deploy:
    placement:
       constraints: [node.role==manager]

volumes:
    mongo-volume:
networks:
    gui-back-auth-1:
    mongo-back-auth-1:
    adminer-1:
secrets:
  db-password-secret:
    file: ./Secrets/db-secret-password.txt
  db-user-secret:
    file: ./Secrets/db-secret-user.txt
  db-secret-uri:
    file: ./Secrets/db-secret-uri.txt
  db-secret-jwt:
    file: ./Secrets/db-secret-jwt.txt