version: "3.8"


services:
  gui:
    image: gui
    ports:
      - "3001:3000"
    environment:
      GUI_API_ROUTE: gui-service/api
      NODE_ENV: development
    networks:
       - gui-back-auth-1
      
  auth:
    image: auth
    ports:
      - "4000:4000"
    environment:
      AUTH_API_ROUTE: auth-service/api
      MONGO_URI: db-secret-uri
      JWT_SECRET: db-secret-jwt
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
       - gui-back-auth-1
       - mongo-back-auth-1

  studclass:
    image: studclass
    ports:
      - "5000:5000"
    environment:
      studclass_API_ROUTE: studclass-service/api
      MONGO_URI: db-secret-uri
      NODE_ENV: development
    depends_on: 
      - mongo
    networks:
       - gui-back-auth-1
       - mongo-back-auth-1

  mongo:
    image: mongo:4.4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/mongo
    networks:
       - mongo-back-auth-1
       - adminer-1
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: db-secret-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: db-secret-password
    networks:
       - adminer-1

volumes:
    mongo-volume:

networks:
    gui-back-auth-1:
    mongo-back-auth-1:
    adminer-1:

secrets:
  db-password-secret:
    file: ./Secrets/db-secret-password.txt
  db-user-secret:
    file: ./Secrets/db-secret-user.txt
  db-secret-uri:
    file: ./Secrets/db-secret-uri.txt
  db-secret-jwt:
    file: ./Secrets/db-secret-jwt.txt
