version: "3.8"


services:
  gui:
    image: gui
    ports:
      - "3001:3000"
    environment:
      GUI_API_ROUTE: gui-service/api
      NODE_ENV: development

  auth:
    image: auth
    ports:
      - "4000:4000"
    environment:
      AUTH_API_ROUTE: auth-service/api
      NODE_ENV: development
    depends_on:
      - mongo

  studclass:
    image: studclass
    ports:
      - 5000:5000
    environment:
      studclass_API_ROUTE: studclass-service/api
      NODE_ENV: development
    links: 
      - mongo

  mongo:
    image: mongo:4.4.2
    ports:
      - "27017:27017"
    


